language: python
cache: pip
python:
  - "2.7"
  - "3.5"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-dev libxslt-dev python-qt4
  # Old version
  - sudo apt-get remove python-openssl

before_script:
  # We need a (fake) display on Travis so I need to start a X server.
  - export DISPLAY=:99.0
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render

script:
  - pip install .
  - py.test tests --cov inkcut --cov-report xml -v

after_success:
  - codecov
